
from .views import *
from django.urls import path, include, re_path
from django.conf.urls import url

app_name = 'user'

urlpatterns = [ 
    path('login', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name = 'register'),
    re_path(r'complete-registration/(?P<pk>[0-9]+)', CompleteRegistrationView.as_view(), name = 'complete-registration'),
    path('login-phone', LoginPhoneNumberView.as_view(), name='login-phone'),
    path('logout', logout_request, name='logout'),
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('dashboard_auto_refresh', DashboardAutoRefresh.as_view(), name='dashboard_auto_refresh'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('save-profile-picture', saveprofilepicture, name='save-profile-picture'),
    path('chat', chat, name='chat'),
    path('user-connections', UserConnectionsView.as_view(), name='user-connections'),
    path('maps', MapView.as_view(), name='maps'),
    # path('preferences', preferences, name='preferences'),
    path('preferences', EditPreferencesView.as_view(), name='preferences'),
    path('help', help, name='help'),
    path('frontend/login/', Login.as_view(), name = 'website-login-api'),
    path('frontend/get-user-details/', GetUserDetails.as_view(), name = 'website-get-user-details'),
    path('frontend/get-allergies-list/', GetAllergiesList.as_view(), name = 'website-get-allergies-list'),
    path('frontend/update-user-profile/', UpdateUserProfile.as_view(), name = 'update-user-profile-api'),
    path('frontend/update-user-links/', UpdateUserLinks.as_view(), name = 'update-user-links-api'),
    path('frontend/users-list/', GetUsersList.as_view(), name = 'website-users-list'),
    path('frontend/dashboard-data/', DashboardData.as_view(), name = 'website-dashboard-data'),
    path('frontend/upload-excel/', UploadExcel.as_view(), name = 'website-users-list'),
    path('frontend/get-logged-in-user-details/', GetLoggedInUserDetails.as_view(), name = 'frontend/get-logged-in-user-details'),
    path('frontend/update-profile-picture/', UpdateProfilePicture.as_view(), name = 'frontend/update-profile-picture'),
    path('firebase-save', FirebaseSave.as_view(), name = 'firebase-save'),
    path('firebase-login-redirect', firebaseloginredirect, name = 'firebase-login-redirect'),
    path('edit-allergies', EditAllergiesView.as_view(), name = 'edit-allergies'),
    path('calendar', CalendarView.as_view(), name='calendar'),
    path('patients', PatientsView.as_view(), name='patients'), 
    path('add-doctor', AddDoctorView.as_view(), name='add-doctor'),
    path('remove-doctor/<pk>', RemoveDoctorView.as_view(), name='remove-doctor'),
    path('add-caretaker', AddCaretakerView.as_view(), name='add-caretaker'),
    path('remove-caretaker/<pk>', RemoveCaretakerView.as_view(), name='remove-caretaker'),
    path('add-pharmacy', AddPharmacyView.as_view(), name='add-pharmacy'),
    path('edit-pharmacy/<pk>', EditPharmacyView.as_view(), name='edit-pharmacy'),
    path('delete-pharmacy/<pk>', DeletePharmacyView.as_view(), name='delete-pharmacy'),
    path('add-emergency-contact', AddEmergencyContactView.as_view(), name='add-emergency-contact'),
    path('edit-emergency-contact/<pk>', EditEmergencyContactView.as_view(), name='edit-emergency-contact'),
    path('delete-emergency-contact/<pk>', DeleteEmergencyContactView.as_view(), name='delete-emergency-contact'),
    path('notifications', NotificationsView.as_view(), name='notifications'),
    path('view-notification/<pk>', ViewNotificationView.as_view(), name='view-notification'),
    path('approve-notification/<pk>', approve_notification, name='approve-notification'),
    path('reject-notification/<pk>', reject_notification, name='reject-notification'),
    path('mark-all-read', mark_all_read, name='mark-all-read'),
    path('patient-details/<pk>', PatientDetailsView.as_view(), name='patient-details'),
    path('appointments/<pk>', AppointmentsListView.as_view(), name='appointments'),
    path('add-appointment/<pk>/<redirect_type>', AddAppointmentView.as_view(), name='add-appointment'),
    path('edit-appointment/<pk>/<redirect_type>', EditAppointmentView.as_view(), name='edit-appointment'),
    path('delete-appointment/<pk>/<redirect_type>', DeleteAppointmentView.as_view(), name='delete-appointment'),
    path('prescriptions/<pk>', PrescriptionsListView.as_view(), name='prescriptions'),
    path('add-prescription/<pk>', AddPrescriptionView.as_view(), name='add-prescription'),
    path('edit-prescription/<pk>', EditPrescriptionView.as_view(), name='edit-prescription'),
    path('delete-prescription/<pk>', DeletePrescriptionView.as_view(), name='delete-prescription'),
    path('dashboard-chart-data/<pk>', DashboardChartDataView.as_view(), name='dashboard-chart-data'),
]